name: local_data
description: Package to handle local data persistence
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
dependencies:
  path: ^1.8.3
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  sqflite_migration: ^0.3.0
